TYPO3:
  Flow:
    security:
      enable: TRUE
      authentication:
        #authenticationStrategy: oneToken atLeastOneToken anyToken see: http://docs.typo3.org/flow/TYPO3FlowDocumentation/TheDefinitiveGuide/PartIII/Security.html#multi-factor-authentication-strategy
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider